# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.0' # replace this value with the version that you need for your project
  displayName: 'install .NET Core 2.0'

- script: dotnet restore
  displayName: 'restore packages'

- script: dotnet build ABDService --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
